import { InMemoryDbService } from "angular-in-memory-web-api";
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const animes = [{'anime_description': "Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture.\n\r\nOne day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki's body! Elsewhere, Taki finds himself living Mitsuha's life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another.\n\nKimi no Na wa. revolves around Mitsuha and Taki's actions, which begin to have a dramatic impact on each other's lives, weaving them into a fabric held together by fate and circumstance.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Supernatural', 'Drama', 'Romance', 'School'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/5/87048.jpg',
  'anime_link': 'https://myanimelist.net/anime/32281/Kimi_no_Na_wa',
  'anime_score': '9.26',
  'anime_video': 'https://www.youtube.com/embed/3KR8_igDs1Y',
  'id': 1,
  'name': 'Kimi no Na wa'},
 {'anime_description': '"In order for something to be obtained, something of equal value must be lost."\n\r\nAlchemy is bound by this Law of Equivalent Exchange—something the young brothers Edward and Alphonse Elric only realize after attempting human transmutation: the one forbidden act of alchemy. They pay a terrible price for their transgression—Edward loses his left leg, Alphonse his physical body. It is only by the desperate sacrifice of Edward\'s right arm that he is able to affix Alphonse\'s soul to a suit of armor. Devastated and alone, it is the hope that they would both eventually return to their original bodies that gives Edward the inspiration to obtain metal limbs called "automail" and become a state alchemist, the Fullmetal Alchemist.\n\r\nThree years of searching later, the brothers seek the Philosopher\'s Stone, a mythical relic that allows an alchemist to overcome the Law of Equivalent Exchange. Even with military allies Colonel Roy Mustang, Lieutenant Riza Hawkeye, and Lieutenant Colonel Maes Hughes on their side, the brothers find themselves caught up in a nationwide conspiracy that leads them not only to the true nature of the elusive Philosopher\'s Stone, but their country\'s murky history as well. In between finding a serial killer and racing against time, Edward and Alphonse must ask themselves if what they are doing will make them human again... or take away their humanity.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action',
   'Military',
   'Adventure',
   'Comedy',
   'Drama',
   'Magic',
   'Fantasy',
   'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/5/47421.jpg',
  'anime_link': 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood',
  'anime_score': '9.25',
  'anime_video': 'https://www.youtube.com/embed/1IIgtdFWvBI',
  'id': 2,
  'name': 'Fullmetal Alchemist: Brotherhoo'},
 {'anime_description': 'Second season of Owarimonogatari.',
  'anime_genre': ['Mystery', 'Comedy', 'Supernatural'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/6/87322.jpg',
  'anime_link': 'https://myanimelist.net/anime/35247/Owarimonogatari_2nd_Season',
  'anime_score': '9.24',
  'anime_video': 'https://www.youtube.com/embed/7WdyIcDlK2o',
  'id': 3,
  'name': 'Owarimonogatari 2nd Seaso'},
 {'anime_description': "Gintoki, Shinpachi, and Kagura return as the fun-loving but broke members of the Yorozuya team! Living in an alternate-reality Edo, where swords are prohibited and alien overlords have conquered Japan, they try to thrive on doing whatever work they can get their hands on. However, Shinpachi and Kagura still haven't been paid... Does Gin-chan really spend all that cash playing pachinko?\n\r\nMeanwhile, when Gintoki drunkenly staggers home one night, an alien spaceship crashes nearby. A fatally injured crew member emerges from the ship and gives Gintoki a strange, clock-shaped device, warning him that it is incredibly powerful and must be safeguarded. Mistaking it for his alarm clock, Gintoki proceeds to smash the device the next morning and suddenly discovers that the world outside his apartment has come to a standstill. With Kagura and Shinpachi at his side, he sets off to get the device fixed; though, as usual, nothing is ever that simple for the Yorozuya team.\n\r\nFilled with tongue-in-cheek humor and moments of heartfelt emotion, Gintama's third season finds Gintoki and his friends facing both their most hilarious misadventures and most dangerous crises yet.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Action',
   'Comedy',
   'Historical',
   'Parody',
   'Samurai',
   'Sci-Fi',
   'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/3/72078.jpg',
  'anime_link': 'https://myanimelist.net/anime/28977/Gintama',
  'anime_score': '9.20',
  'anime_video': 'https://www.youtube.com/embed/W_eWXh85VS4',
  'id': 4,
  'name': 'Gintama'},
 {'anime_description': 'The self-proclaimed mad scientist Rintarou Okabe rents out a room in a rickety old building in Akihabara, where he indulges himself in his hobby of inventing prospective "future gadgets" with fellow lab members: Mayuri Shiina, his air-headed childhood friend, and Hashida Itaru, a perverted hacker nicknamed "Daru." The three pass the time by tinkering with their most promising contraption yet, a machine dubbed the "Phone Microwave," which performs the strange function of morphing bananas into piles of green gel.\n\r\nThough miraculous in itself, the phenomenon doesn\'t provide anything concrete in Okabe\'s search for a scientific breakthrough; that is, until the lab members are spurred into action by a string of mysterious happenings before stumbling upon an unexpected success—the Phone Microwave can send emails to the past, altering the flow of history.\n\r\nAdapted from the critically acclaimed visual novel by 5pb. and Nitroplus, Steins;Gate takes Okabe through the depths of scientific theory and practicality. Forced across the diverging threads of past and present, Okabe must shoulder the burdens that come with holding the key to the realm of time.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Sci-Fi', 'Thriller'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/5/73199.jpg',
  'anime_link': 'https://myanimelist.net/anime/9253/Steins_Gate',
  'anime_score': '9.15',
  'anime_video': 'https://www.youtube.com/embed/27OZc-ku6is',
  'id': 5,
  'name': 'Steins;Gat'},
 {'anime_description': "After a one-year hiatus, Shinpachi Shimura returns to Edo, only to stumble upon a shocking surprise: Gintoki and Kagura, his fellow Yorozuya members, have become completely different characters! Fleeing from the Yorozuya headquarters in confusion, Shinpachi finds that all the denizens of Edo have undergone impossibly extreme changes, in both appearance and personality. Most unbelievably, his sister Otae has married the Shinsengumi chief and shameless stalker Isao Kondou and is pregnant with their first child.\n\r\nBewildered, Shinpachi agrees to join the Shinsengumi at Otae and Kondou's request and finds even more startling transformations afoot both in and out of the ranks of the the organization. However, discovering that Vice Chief Toushirou Hijikata has remained unchanged, Shinpachi and his unlikely Shinsengumi ally set out to return the city of Edo to how they remember it.\n\r\nWith even more dirty jokes, tongue-in-cheek parodies, and shameless references, Gintama' follows the Yorozuya team through more of their misadventures in the vibrant, alien-filled world of Edo.\n\r\n[Written by MAL Rewrite]\n",
  'anime_genre': ['Action',
   'Sci-Fi',
   'Comedy',
   'Historical',
   'Parody',
   'Samurai',
   'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/4/50361.jpg',
  'anime_link': 'https://myanimelist.net/anime/9969/Gintama',
  'anime_score': '9.13',
  'id': 6,
  'name': 'Gintama&#039'},
 {'anime_description': 'Hunter x Hunter is set in a world where Hunters exist to perform all manner of dangerous tasks like capturing criminals and bravely searching for lost treasures in uncharted territories. Twelve-year-old Gon Freecss is determined to become the best Hunter possible in hopes of finding his father, who was a Hunter himself and had long ago abandoned his young son. However, Gon soon realizes the path to achieving his goals is far more challenging than he could have ever imagined.\n\r\nAlong the way to becoming an official Hunter, Gon befriends the lively doctor-in-training Leorio, vengeful Kurapika, and rebellious ex-assassin Killua. To attain their own goals and desires, together the four of them take the Hunter Exam, notorious for its low success rate and high probability of death. Throughout their journey, Gon and his friends embark on an adventure that puts them through many hardships and struggles. They will meet a plethora of monsters, creatures, and characters—all while learning what being a Hunter truly means.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action', 'Adventure', 'Super Power', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/11/33657.jpg',
  'anime_link': 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011',
  'anime_score': '9.12',
  'anime_video': 'https://www.youtube.com/embed/D9iTQRB4XRk',
  'id': 7,
  'name': 'Hunter x Hunter (2011'},
 {'anime_description': "The 150-year-long stalemate between the two interstellar superpowers, the Galactic Empire and the Free Planets Alliance, comes to an end when a new generation of leaders arises: the idealistic military genius Reinhard von Lohengramm, and the FPA's reserved historian, Yang Wenli.\n\r\nWhile Reinhard climbs the ranks of the Empire with the aid of his childhood friend, Siegfried Kircheis, he must fight not only the war, but also the remnants of the crumbling Goldenbaum Dynasty in order to free his sister from the Kaiser and unify humanity under one genuine ruler. Meanwhile, on the other side of the galaxy, Yang—a strong supporter of democratic ideals—has to stand firm in his beliefs, despite the struggles of the FPA, and show his pupil, Julian Mintz, that autocracy is not the solution.\n\r\nAs ideologies clash amidst the war's many casualties, the two strategic masterminds must ask themselves what the real reason behind their battle is.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Military', 'Sci-Fi', 'Space', 'Drama'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/13/13225.jpg',
  'anime_link': 'https://myanimelist.net/anime/820/Ginga_Eiyuu_Densetsu',
  'anime_score': '9.11',
  'anime_video': 'https://www.youtube.com/embed/G7grjXe2Eyo',
  'id': 8,
  'name': 'Ginga Eiyuu Densets'},
 {'anime_description': 'Sakata Gintoki, Kagura, and Shinpachi Shimura continue to scrape a living as freelance jack-of-all-trades at Edo while amidst the several odd humans and aliens that inhabit the peculiar metropolis. \n\r\n(Source: ANN) \n\r\nThis season contains episodes that were aired in the previous seasons of Gintama. For complete episode information, see the More Info tab.',
  'anime_genre': ['Action',
   'Comedy',
   'Historical',
   'Parody',
   'Samurai',
   'Sci-Fi',
   'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/6/75172.jpg',
  'anime_link': 'https://myanimelist.net/anime/15417/Gintama__Enchousen',
  'anime_score': '9.08',
  'id': 9,
  'name': 'Gintama&#039;: Enchouse'},
 {'anime_description': "As a wild youth, elementary school student Shouya Ishida sought to beat boredom in the cruelest ways. When the deaf Shouko Nishimiya transfers into his class, Shouya and the rest of his class thoughtlessly bully her for fun. However, when her mother notifies the school, he is singled out and blamed for everything done to her. With Shouko transferring out of the school, Shouya is left at the mercy of his classmates. He is heartlessly ostracized all throughout elementary and middle school, while teachers turn a blind eye.\n\r\nNow in his third year of high school, Shouya is still plagued by his wrongdoings as a young boy. Sincerely regretting his past actions, he sets out on a journey of redemption: to meet Shouko once more and make amends.\n\nKoe no Katachi tells the heartwarming tale of Shouya's reunion with Shouko and his honest attempts to redeem himself, all while being continually haunted by the shadows of his past.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Drama', 'School', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/3/80136.jpg',
  'anime_link': 'https://myanimelist.net/anime/28851/Koe_no_Katachi',
  'anime_score': '9.08',
  'anime_video': 'https://www.youtube.com/embed/XBNWo25izJ8',
  'id': 10,
  'name': 'Koe no Katach'},
 {'anime_description': 'When Gintoki apprehends a movie pirate at a premiere, he checks the camera\'s footage and finds himself transported to a bleak, post-apocalyptic version of Edo, where a mysterious epidemic called the "White Plague" has ravished the world\'s population. It turns out that the movie pirate wasn\'t a pirate after all—it was an android time machine, and Gintoki has been hurtled five years into the future! Shinpachi and Kagura, his Yorozuya cohorts, have had a falling out and are now battle-hardened solo vigilantes and he himself has been missing for years, disappearing without a trace after scribbling a strange message in his journal.\n\r\nSetting out in the disguise given to him by the android time machine, Gintoki haphazardly reunites the Yorozuya team to investigate the White Plague, and soon discovers that the key to saving the future lies in the darkness of his own past. Determined to confront a powerful foe, he makes an important discovery—with a ragtag band of friends and allies at his side, he doesn\'t have to fight alone.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action',
   'Sci-Fi',
   'Comedy',
   'Historical',
   'Parody',
   'Samurai',
   'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/10/51723.jpg',
  'anime_link': 'https://myanimelist.net/anime/15335/Gintama_Movie_2__Kanketsu-hen_-_Yorozuya_yo_Eien_Nare',
  'anime_score': '9.06',
  'anime_video': 'https://www.youtube.com/embed/UhJM5rVqaF8',
  'id': 11,
  'name': 'Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nar'},
 {'anime_description': 'Season 5 of Gintama. ',
  'anime_genre': ['Action',
   'Comedy',
   'Historical',
   'Parody',
   'Samurai',
   'Sci-Fi',
   'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/3/83528.jpg',
  'anime_link': 'https://myanimelist.net/anime/34096/Gintama',
  'anime_score': '9.04',
  'anime_video': 'https://www.youtube.com/embed/LOdAAEJiebM',
  'id': 12,
  'name': 'Gintama'},
 {'anime_description': "Clannad: After Story, the sequel to the critically acclaimed slice-of-life series Clannad, begins after Tomoya Okazaki and Nagisa Furukawa graduate from high school. Together, they experience the emotional rollercoaster of growing up. Unable to decide on a course for his future, Tomoya learns the value of a strong work ethic and discovers the strength of Nagisa's support. Through the couple's dedication and unity of purpose, they push forward to confront their personal problems, deepen their old relationships, and create new bonds.\n\r\nTime also moves on in the Illusionary World. As the plains grow cold with the approach of winter, the Illusionary Girl and the Garbage Doll are presented with a difficult situation that reveals the World's true purpose.\n\r\nBased on the visual novel by Key and produced by Kyoto Animation, Clannad: After Story is an impactful drama highlighting the importance of family and the struggles of adulthood.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Drama',
   'Fantasy',
   'Romance',
   'Slice of Life',
   'Supernatural'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/13/24647.jpg',
  'anime_link': 'https://myanimelist.net/anime/4181/Clannad__After_Story',
  'anime_score': '9.03',
  'anime_video': 'https://www.youtube.com/embed/WiTwXIAcm5Q',
  'id': 13,
  'name': 'Clannad: After Stor'},
 {'anime_description': 'The Amanto, aliens from outer space, have invaded Earth and taken over feudal Japan. As a result, a prohibition on swords has been established, and the samurai of Japan are treated with disregard as a consequence.\n\r\nHowever one man, Gintoki Sakata, still possesses the heart of the samurai, although from his love of sweets and work as a yorozuya, one might not expect it. Accompanying him in his jack-of-all-trades line of work are Shinpachi Shimura, a boy with glasses and a strong heart, Kagura with her umbrella and seemingly bottomless stomach, as well as Sadaharu, their oversized pet dog. Of course, these odd jobs are not always simple, as they frequently have run-ins with the police, ragtag rebels, and assassins, oftentimes leading to humorous but unfortunate consequences.\n\r\nWho said life as an errand boy was easy?\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action',
   'Sci-Fi',
   'Comedy',
   'Historical',
   'Parody',
   'Samurai',
   'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/2/10038.jpg',
  'anime_link': 'https://myanimelist.net/anime/918/Gintama',
  'anime_score': '9.02',
  'id': 14,
  'name': 'Gintam'},
 {'anime_description': 'The third season of Haikyuu!!',
  'anime_genre': ['Comedy', 'Sports', 'Drama', 'School', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/7/81992.jpg',
  'anime_link': 'https://myanimelist.net/anime/32935/Haikyuu__Karasuno_Koukou_VS_Shiratorizawa_Gakuen_Koukou',
  'anime_score': '9.02',
  'anime_video': 'https://www.youtube.com/embed/EHYdxpvcBEs',
  'id': 15,
  'name': 'Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Kouko'},
 {'anime_description': "One year has passed since the Black Rebellion, a failed uprising against the Holy Britannian Empire led by the masked vigilante Zero, who is now missing. At a loss without their revolutionary leader, Area 11's resistance group—the Black Knights—find themselves too powerless to combat the brutality inflicted upon the Elevens by Britannia, which has increased significantly in order to crush any hope of a future revolt. \n\r\nLelouch Lamperouge, having lost all memory of his double life, is living peacefully alongside his friends as a high school student at Ashford Academy. His former partner C.C., unable to accept this turn of events, takes it upon herself to remind him of his past purpose, hoping that the mastermind Zero will rise once again to finish what he started, in this thrilling conclusion to the series.\n\r\n[Written by MAL Rewrite]\n",
  'anime_genre': ['Action',
   'Military',
   'Sci-Fi',
   'Super Power',
   'Drama',
   'Mecha'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/4/9391.jpg',
  'anime_link': 'https://myanimelist.net/anime/2904/Code_Geass__Hangyaku_no_Lelouch_R2',
  'anime_score': '8.96',
  'anime_video': 'https://www.youtube.com/embed/dpYkVRyLC4o',
  'id': 16,
  'name': 'Code Geass: Hangyaku no Lelouch R'},
 {'anime_description': "Stubborn, spoiled, and naïve, 10-year-old Chihiro Ogino is less than pleased when she and her parents discover an abandoned amusement park on the way to their new house. Cautiously venturing inside, she realizes that there is more to this place than meets the eye, as strange things begin to happen once dusk falls. Ghostly apparitions and food that turns her parents into pigs are just the start—Chihiro has unwittingly crossed over into the spirit world. Now trapped, she must summon the courage to live and work amongst spirits, with the help of the enigmatic Haku and the cast of unique characters she meets along the way.\n\r\nVivid and intriguing, Sen to Chihiro no Kamikakushi tells the story of Chihiro's journey through an unfamiliar world as she strives to save her parents and return home.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Adventure', 'Supernatural', 'Drama'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/6/79597.jpg',
  'anime_link': 'https://myanimelist.net/anime/199/Sen_to_Chihiro_no_Kamikakushi',
  'anime_score': '8.93',
  'anime_video': 'https://www.youtube.com/embed/ByXuk9QqQkk',
  'id': 17,
  'name': 'Sen to Chihiro no Kamikakush'},
 {'anime_description': 'With help from Meme Oshino, the apparition specialist, Koyomi defeats the three powerful vampire hunters: Dramaturgy, Episode and Guillotinecutter.\n\r\nKoyomi takes back all the limbs of Kiss-Shot-Acerola-Orion-Heart-Underblade in order to become a human again.\n\r\nBut, when he returns to Kiss-Shot, she reveals to him the cold truth of what it means to be a vampire—a creature of the night. Unable to take back what he has done, Koyomi feels nothing but regret and can only deny his dreadful fate. While Koyomi is struggling to face reality, his "friend" Tsubasa Hanekawa comes to him with a certain plan…\n\r\n(Source: Aniplex USA)',
  'anime_genre': ['Action', 'Mystery', 'Supernatural', 'Vampire'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/8/82911.jpg',
  'anime_link': 'https://myanimelist.net/anime/31758/Kizumonogatari_III__Reiketsu-hen',
  'anime_score': '8.92',
  'anime_video': 'https://www.youtube.com/embed/4nTLr6Uf9Ug',
  'id': 18,
  'name': 'Kizumonogatari III: Reiketsu-he'},
 {'anime_description': "Following their participation at the Inter-High, the Karasuno High School volleyball team attempts to refocus their efforts, aiming to conquer the Spring tournament instead. \n\r\nWhen they receive an invitation from long-standing rival Nekoma High, Karasuno agrees to take part in a large training camp alongside many notable volleyball teams in Tokyo and even some national level players. By playing with some of the toughest teams in Japan, they hope not only to sharpen their skills, but also come up with new attacks that would strengthen them. Moreover, Hinata and Kageyama attempt to devise a more powerful weapon, one that could possibly break the sturdiest of blocks. \n\r\nFacing what may be their last chance at victory before the senior players graduate, the members of Karasuno's volleyball team must learn to settle their differences and train harder than ever if they hope to overcome formidable opponents old and new—including their archrival Aoba Jousai and its world-class setter Tooru Oikawa.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Comedy', 'Sports', 'Drama', 'School', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/9/76662.jpg',
  'anime_link': 'https://myanimelist.net/anime/28891/Haikyuu_Second_Season',
  'anime_score': '8.90',
  'anime_video': 'https://www.youtube.com/embed/Z9qXOEwiTGQ',
  'id': 19,
  'name': 'Haikyuu!! Second Seaso'},
 {'anime_description': "Music accompanies the path of the human metronome, the prodigious pianist Kousei Arima. But after the passing of his mother, Saki Arima, Kousei falls into a downward spiral, rendering him unable to hear the sound of his own piano.\n\r\nTwo years later, Kousei still avoids the piano, leaving behind his admirers and rivals, and lives a colorless life alongside his friends Tsubaki Sawabe and Ryouta Watari. However, everything changes when he meets a beautiful violinist, Kaori Miyazono, who stirs up his world and sets him on a journey to face music again.\n\r\nBased on the manga series of the same name, Shigatsu wa Kimi no Uso approaches the story of Kousei's recovery as he discovers that music is more than playing each note perfectly, and a single melody can bring in the fresh spring air of April.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Drama', 'Music', 'Romance', 'School', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/3/67177.jpg',
  'anime_link': 'https://myanimelist.net/anime/23273/Shigatsu_wa_Kimi_no_Uso',
  'anime_score': '8.90',
  'anime_video': 'https://www.youtube.com/embed/AbTfMbmucpI',
  'id': 20,
  'name': 'Shigatsu wa Kimi no Us'},
 {'anime_description': "Ex-convict turned Rakugo apprentice Yotarou has finally taken the name of Yurakutei Sukeroku III, and with his master Yakumo's permission has attained the lofty rank of shin'uchi. He assumes the name at a critical time for Rakugo, with audiences fewer than ever. At the same time he has started acting as a husband to Konatsu, who is now a single mother. Yotarou thus begins the struggle to fill the role of Sukeroku, both as the future of Rakugo and as a part of Yakumo's and Konatsu's lives.\n\r\n(Source: ANN)",
  'anime_genre': ['Drama', 'Josei'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/10/82947.jpg',
  'anime_link': 'https://myanimelist.net/anime/33095/Shouwa_Genroku_Rakugo_Shinjuu__Sukeroku_Futatabi-hen',
  'anime_score': '8.89',
  'anime_video': 'https://www.youtube.com/embed/wxFCi-ybQ5k',
  'id': 21,
  'name': 'Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-he'},
 {'anime_description': 'Second season of Mushishi Zoku Shou.',
  'anime_genre': ['Adventure',
   'Fantasy',
   'Historical',
   'Mystery',
   'Seinen',
   'Slice of Life',
   'Supernatural'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/9/68095.jpg',
  'anime_link': 'https://myanimelist.net/anime/24701/Mushishi_Zoku_Shou_2nd_Season',
  'anime_score': '8.85',
  'anime_video': 'https://www.youtube.com/embed/zuX3P6ynAgc',
  'id': 22,
  'name': 'Mushishi Zoku Shou 2nd Seaso'},
 {'anime_description': 'At UA Academy, not even a violent attack can disrupt their most prestigious event: the school sports festival. Renowned across Japan, this festival is an opportunity for aspiring heroes to showcase their abilities, both to the public and potential recruiters.\n\r\nHowever, the path to glory is never easy, especially for Izuku Midoriya—whose quirk possesses great raw power but is also cripplingly inefficient. Pitted against his talented classmates, such as the fire and ice wielding Shouto Todoroki, Izuku must utilize his sharp wits and master his surroundings to achieve victory and prove to the world his worth.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action', 'Comedy', 'Super Power', 'School', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/12/85221.jpg',
  'anime_link': 'https://myanimelist.net/anime/33486/Boku_no_Hero_Academia_2nd_Season',
  'anime_score': '8.83',
  'anime_video': 'https://www.youtube.com/embed/ayeDDe8eN1E',
  'id': 23,
  'name': 'Boku no Hero Academia 2nd Seaso'},
 {'anime_description': 'In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind. The Inter Solar System Police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as "Cowboys." The ragtag team aboard the spaceship Bebop are two such individuals.\n\r\nMellow and carefree Spike Spiegel is balanced by his boisterous, pragmatic partner Jet Black as the pair makes a living chasing bounties and collecting rewards. Thrown off course by the addition of new members that they meet in their travels—Ein, a genetically engineered, highly intelligent Welsh Corgi; femme fatale Faye Valentine, an enigmatic trickster with memory loss; and the strange computer whiz kid Edward Wong—the crew embarks on thrilling adventures that unravel each member\'s dark and mysterious past little by little.\n\r\nWell-balanced with high density action and light-hearted comedy, Cowboy Bebop is a space Western classic and an homage to the smooth and improvised music it is named after.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action', 'Adventure', 'Comedy', 'Drama', 'Sci-Fi', 'Space'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/4/19644.jpg',
  'anime_link': 'https://myanimelist.net/anime/1/Cowboy_Bebop',
  'anime_score': '8.81',
  'anime_video': 'https://www.youtube.com/embed/qig4KOK2R2g',
  'id': 24,
  'name': 'Cowboy Bebo'},
 {'anime_description': "Makunouchi Ippo has been bullied his entire life. Constantly running errands and being beaten up by his classmates, Ippo has always dreamed of changing himself, but never has the passion to act upon it. One day, in the midst of yet another bullying, Ippo is saved by Takamura Mamoru, who happens to be a boxer. Ippo faints from his injuries and is brought to the Kamogawa boxing gym to recover. As he regains consciousness, he is awed and amazed at his new surroundings in the gym, though lacks confidence to attempt anything. Takamura places a photo of Ippo's classmate on a punching bag and forces him to punch it. It is only then that Ippo feels something stir inside him and eventually asks Takamura to train him in boxing. Thinking that Ippo does not have what it takes, Takamura gives him a task deemed impossible and gives him a one week time limit. With a sudden desire to get stronger, for himself and his hard working mother, Ippo trains relentlessly to accomplish the task within the time limit. Thus Ippo's journey to the top of the boxing world begins.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Comedy', 'Sports', 'Drama', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/10/2025.jpg',
  'anime_link': 'https://myanimelist.net/anime/263/Hajime_no_Ippo',
  'anime_score': '8.81',
  'anime_video': 'https://www.youtube.com/embed/7xM3XTJUhPk',
  'id': 25,
  'name': 'Hajime no Ipp'},
 {'anime_description': "When mankind's savagery surpasses his fear of death, there is little hope for those who wish to live honest lives. Beneath a full moon, a young boy witnesses the murder of the bandits who had enslaved him, and is then christened with a new name by the man who rescued him. This boy is Shinta, now known as Kenshin Himura, and he is destined to become a swordsman. The softness of his heart does not befit the occupation, but his desire to protect the innocent is absolute.\n\nRurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen details the origins of the man who would bear the name of Hitokiri Battousai long before he swore his oath not to kill and before he earned his reputation as an assassin. The young man’s heart is divided between justice and corruption, while the fate of a nation rests on his actions.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Action',
   'Historical',
   'Drama',
   'Romance',
   'Martial Arts',
   'Samurai'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/9/13160.jpg',
  'anime_link': 'https://myanimelist.net/anime/44/Rurouni_Kenshin__Meiji_Kenkaku_Romantan_-_Tsuioku-hen',
  'anime_score': '8.81',
  'id': 26,
  'name': 'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-he'},
 {'anime_description': 'In the year 2010, the Holy Empire of Britannia is establishing itself as a dominant military nation, starting with the conquest of Japan. Renamed to Area 11 after its swift defeat, Japan has seen significant resistance against these tyrants in an attempt to regain independence.\n\r\nLelouch Lamperouge, exiled prince of Britannia, unfortunately finds himself caught in a crossfire between the two nations\' armed forces. He is able to escape, however, thanks to the timely appearance of a mysterious girl named C.C., who bestows upon him Geass, the "Power of Kings." Realizing the vast potential of his newfound "power of absolute obedience," Lelouch embarks upon a perilous journey as the masked vigilante known as Zero, leading a merciless onslaught against Britannia in order to get revenge once and for all.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action',
   'Mecha',
   'Military',
   'School',
   'Sci-Fi',
   'Super Power'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/5/50331.jpg',
  'anime_link': 'https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch',
  'anime_score': '8.80',
  'anime_video': 'https://www.youtube.com/embed/DR1d_Pm729o',
  'id': 27,
  'name': 'Code Geass: Hangyaku no Lelouc'},
 {'anime_description': "When an Emishi village is attacked by a fierce demon boar, the young prince Ashitaka puts his life at stake to defend his tribe. With its dying breath, the beast curses the prince's arm, granting him demonic powers while gradually siphoning his life away. Instructed by the village elders to travel westward for a cure, Ashitaka arrives at Tatara, the Iron Town, where he finds himself embroiled in a fierce conflict: Lady Eboshi of Tatara, promoting constant deforestation, stands against Princess San and the sacred spirits of the forest, who are furious at the destruction brought by the humans. As the opposing forces of nature and mankind begin to clash in a desperate struggle for survival, Ashitaka attempts to seek harmony between the two, all the while battling the latent demon inside of him. Princess Mononoke is a tale depicting the connection of technology and nature, while showing the path to harmony that could be achieved by mutual acceptance.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Action', 'Adventure', 'Fantasy'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/7/75919.jpg',
  'anime_link': 'https://myanimelist.net/anime/164/Mononoke_Hime',
  'anime_score': '8.80',
  'anime_video': 'https://www.youtube.com/embed/4OiMOHRDs14',
  'id': 28,
  'name': 'Mononoke Him'},
 {'anime_description': "Hana, a hard-working college student, falls in love with a mysterious man who attends one of her classes though he is not an actual student. As it turns out, he is not truly human either. On a full moon night, he transforms, revealing that he is the last werewolf alive. Despite this, Hana's love remains strong, and the two ultimately decide to start a family.\n\r\nHana gives birth to two healthy children—Ame, born during rainfall, and Yuki, born during snowfall—both possessing the ability to turn into wolves, a trait inherited from their father. All too soon, however, the sudden death of her lover devastates Hana's life, leaving her to raise a peculiar family completely on her own. The stress of raising her wild-natured children in a densely populated city, all while keeping their identity a secret, culminates in a decision to move to the countryside, where she hopes Ame and Yuki can live a life free from the judgments of society. Wolf Children is the heartwarming story about the challenges of being a single mother in an unforgiving modern world.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Slice of Life', 'Fantasy'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/9/35721.jpg',
  'anime_link': 'https://myanimelist.net/anime/12355/Ookami_Kodomo_no_Ame_to_Yuki',
  'anime_score': '8.80',
  'anime_video': 'https://www.youtube.com/embed/8xLji7WsW0w',
  'id': 29,
  'name': 'Ookami Kodomo no Ame to Yuk'},
 {'anime_description': 'Season 6 of Natsume Yuujinchou.',
  'anime_genre': ['Slice of Life',
   'Supernatural',
   'Drama',
   'Fantasy',
   'Shoujo'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/6/84416.jpg',
  'anime_link': 'https://myanimelist.net/anime/34591/Natsume_Yuujinchou_Roku',
  'anime_score': '8.79',
  'anime_video': 'https://www.youtube.com/embed/xmJz_MyU3bc',
  'id': 30,
  'name': 'Natsume Yuujinchou Rok'},
 {'anime_description': 'Perceived as strange and feared by man, over time the misshapen ones came to be known as Mushi. Although they harbor no ill intentions towards humans, many suffer from the side effects of their existence and strange nature; exploiting the Mushi without understanding them, even unintentionally, can lead to disaster and strife for any involved. Mushishi Zoku Shou continues the story of Mushishi Ginko on his journey to help the visible world to coexist with the Mushi.\n\r\nDuring his travels, Ginko discovers various gifted individuals—those cursed by circumstance and those maintaining a fragile symbiosis with the Mushi—inevitably confronting the question of whether humanity, talented and tortured alike, can manage the responsibility of the unseen. Moreover, as a Mushishi, Ginko must learn more about these strange beings and decide if he has the right to interfere with the complex relationships between Mushi and mankind.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Adventure',
   'Slice of Life',
   'Mystery',
   'Historical',
   'Supernatural',
   'Fantasy',
   'Seinen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/13/58533.jpg',
  'anime_link': 'https://myanimelist.net/anime/21939/Mushishi_Zoku_Shou',
  'anime_score': '8.78',
  'anime_video': 'https://www.youtube.com/embed/CXhPRWY1L0E',
  'id': 31,
  'name': 'Mushishi Zoku Sho'},
 {'anime_description': "Apparitions, oddities, and gods continue to manifest around Koyomi Araragi and his close-knit group of friends: Tsubasa Hanekawa, the group's modest genius; Shinobu Oshino, the resident doughnut-loving vampire; athletic deviant Suruga Kanbaru; bite-happy spirit Mayoi Hachikuji; Koyomi's cutesy stalker Nadeko Sengoku; and Hitagi Senjogahara, the poignant tsundere. \n\nMonogatari Series: Second Season revolves around these individuals and their struggle to overcome the darkness that is rapidly approaching. A new semester has begun and with graduation looming over Koyomi, he must quickly decide the paths he will walk, as well as the relationships and friends that he'll save. But as strange events begin to unfold, Koyomi is nowhere to be found, and a vicious tiger apparition has appeared in his absence. Tsubasa Hanekawa has become its target, and she must fend for herself—or bow to the creature's perspective on the feebleness of humanity. \n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Mystery', 'Comedy', 'Supernatural', 'Romance', 'Vampire'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/3/52133.jpg',
  'anime_link': 'https://myanimelist.net/anime/17074/Monogatari_Series__Second_Season',
  'anime_score': '8.77',
  'anime_video': 'https://www.youtube.com/embed/YrAdRp69BBY',
  'id': 32,
  'name': 'Monogatari Series: Second Seaso'},
 {'anime_description': "One cold Christmas day, Kyon heads over to school and the SOS Brigade's holiday celebration, only to realize that Haruhi Suzumiya seems to have disappeared. Moreover, no one even remembers her or the SOS Brigade; Mikuru Asahina knows nothing and is now afraid of him, and Itsuki Koizumi has also gone missing. The Literature Club, formed only by an uncharacteristically shy Yuki Nagato, now occupies the old SOS club room.\n\nSuzumiya Haruhi no Shoushitsu is based on the fourth light novel of the acclaimed Haruhi series and is set after the events of the anime series. Not uncultured in the supernatural, Kyon will have to deal with his whole life turned upside down like a bad joke, and maybe it's better that way.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Comedy',
   'Mystery',
   'Romance',
   'School',
   'Sci-Fi',
   'Supernatural'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/2/73842.jpg',
  'anime_link': 'https://myanimelist.net/anime/7311/Suzumiya_Haruhi_no_Shoushitsu',
  'anime_score': '8.77',
  'anime_video': 'https://www.youtube.com/embed/eHKyNQopYXo',
  'id': 33,
  'name': 'Suzumiya Haruhi no Shoushits'},
 {'anime_description': '"Mushi": the most basic forms of life in the world. They exist without any goals or purposes aside from simply "being." They are beyond the shackles of the words "good" and "evil." Mushi can exist in countless forms and are capable of mimicking things from the natural world such as plants, diseases, and even phenomena like rainbows.\n\r\nThis is, however, just a vague definition of these entities that inhabit the vibrant world of Mushishi, as to even call them a form of life would be an oversimplification. Detailed information on Mushi is scarce because the majority of humans are unaware of their existence.\n\r\nSo what are Mushi and why do they exist? This is the question that a "Mushishi," Ginko, ponders constantly. Mushishi are those who research Mushi in hopes of understanding their place in the world\'s hierarchy of life.\n\r\nGinko chases rumors of occurrences that could be tied to Mushi, all for the sake of finding an answer.\n\r\nIt could, after all, lead to the meaning of life itself.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Adventure',
   'Fantasy',
   'Historical',
   'Mystery',
   'Seinen',
   'Slice of Life',
   'Supernatural'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/2/73862.jpg',
  'anime_link': 'https://myanimelist.net/anime/457/Mushishi',
  'anime_score': '8.76',
  'anime_video': 'https://www.youtube.com/embed/h371H0KIuPo',
  'id': 34,
  'name': 'Mushish'},
 {'anime_description': "The seemingly ordinary and unimpressive Saitama has a rather unique hobby: being a hero. In order to pursue his childhood dream, he trained relentlessly for three years—and lost all of his hair in the process. Now, Saitama is incredibly powerful, so much so that no enemy is able to defeat him in battle. In fact, all it takes to defeat evildoers with just one punch has led to an unexpected problem—he is no longer able to enjoy the thrill of battling and has become quite bored.\n\r\nThis all changes with the arrival of Genos, a 19-year-old cyborg, who wishes to be Saitama's disciple after seeing what he is capable of. Genos proposes that the two join the Hero Association in order to become certified heroes that will be recognized for their positive contributions to society, and Saitama, shocked that no one knows who he is, quickly agrees. And thus begins the story of One Punch Man, an action-comedy that follows an eccentric individual who longs to fight strong enemies that can hopefully give him the excitement he once felt and just maybe, he'll become popular in the process.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Action',
   'Sci-Fi',
   'Comedy',
   'Parody',
   'Super Power',
   'Supernatural',
   'Seinen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/12/76049.jpg',
  'anime_link': 'https://myanimelist.net/anime/30276/One_Punch_Man',
  'anime_score': '8.76',
  'anime_video': 'https://www.youtube.com/embed/ExUMiF1L0HA',
  'id': 35,
  'name': 'One Punch Ma'},
 {'anime_description': "Onizuka is a reformed biker gang leader who has his sights set on an honorable new ambition: to become the world's greatest teacher... for the purpose of meeting sexy high school girls. Okay, so he's mostly reformed.\n\r\nHowever, strict administrators and a class of ruthless delinquents stand between Onizuka and his goal and they will use any means, however illegal or low, to drive the new teacher away. Perfect, because Onizuka's methods won't be found in any teaching manual; he cares about the difference between legal and illegal activities about as much as he cares for the age difference between himself and a high school girl.\n\r\nSo get ready for math that doesn't add up, language you'd be slapped for using, and biology that would make a grown man blush... unless of course, you're the Great Teacher Onizuka.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Comedy', 'Drama', 'School', 'Shounen', 'Slice of Life'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/13/11460.jpg',
  'anime_link': 'https://myanimelist.net/anime/245/Great_Teacher_Onizuka',
  'anime_score': '8.75',
  'id': 36,
  'name': 'Great Teacher Onizuk'},
 {'anime_description': 'In the spring of his second year of high school, Koyomi Araragi met the beautiful vampire Kiss-shot Acerola-orion Heart-under-blade. Koyomi saved Kiss-shot, who was on the verge of death with all four of her limbs cut off, but only at the expense of becoming her minion and a vampire.\n\r\n"In order to go back to being a human again, you must take back all of Kiss-shot\'s limbs." After receiving advice from Meme Oshino, an expert in the supernatural, Koyomi prepares to go into battle.\n\r\nAwaiting him are three powerful vampire hunters—Dramaturgy, a giant vampire hunter who is a vampire himself. Episode, a half-vampire who wields an enormous cross, and Guillotinecutter, a quiet man who specializes in killing vampires.\n\r\nWill Koyomi be able to take back Kiss-shot\'s limbs from the vampire hunters? Amidst the soft spring rain, the curtain rises on this fateful blood bath…\n\r\n(Source: Aniplex USA)',
  'anime_genre': ['Action', 'Mystery', 'Supernatural', 'Vampire'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/8/80930.jpg',
  'anime_link': 'https://myanimelist.net/anime/31757/Kizumonogatari_II__Nekketsu-hen',
  'anime_score': '8.75',
  'anime_video': 'https://www.youtube.com/embed/nOiEjQy-J7U',
  'id': 37,
  'name': 'Kizumonogatari II: Nekketsu-he'},
 {'anime_description': 'Simon and Kamina were born and raised in a deep, underground village, hidden from the fabled surface. Kamina is a free-spirited loose cannon bent on making a name for himself, while Simon is a timid young boy with no real aspirations. One day while excavating the earth, Simon stumbles upon a mysterious object that turns out to be the ignition key to an ancient artifact of war, which the duo dubs Lagann. Using their new weapon, Simon and Kamina fend off a surprise attack from the surface with the help of Yoko Littner, a hot-blooded redhead wielding a massive gun who wanders the world above.\n\r\nIn the aftermath of the battle, the sky is now in plain view, prompting Simon and Kamina to set off on a journey alongside Yoko to explore the wastelands of the surface. Soon, they join the fight against the "Beastmen," humanoid creatures that terrorize the remnants of humanity in powerful robots called "Gunmen." Although they face some challenges and setbacks, the trio bravely fights these new enemies alongside other survivors to reclaim the surface, while slowly unraveling a galaxy-sized mystery.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action', 'Adventure', 'Comedy', 'Mecha', 'Sci-Fi'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/4/5123.jpg',
  'anime_link': 'https://myanimelist.net/anime/2001/Tengen_Toppa_Gurren_Lagann',
  'anime_score': '8.75',
  'anime_video': 'https://www.youtube.com/embed/rAQylCHv8Cw',
  'id': 38,
  'name': 'Tengen Toppa Gurren Lagan'},
 {'anime_description': "Japanese Featherweight Champion Ippo Makunouchi has successfully defended and retained his title. Meanwhile, his rival, Ichirou Miyata, has resurfaced in Japan, aiming for his own Featherweight belt in the Oriental Pacific Boxing Federation. When the rest of the world comes knocking, however, will Japan's best fighters rise to the challenge and achieve glory at the top? Or will the small island nation be crushed under the weight of greater entities? This time, champions will become challengers issuing a call to the rest of the world and ready to show off their fighting spirit!\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Comedy', 'Sports', 'Drama', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/8/56617.jpg',
  'anime_link': 'https://myanimelist.net/anime/5258/Hajime_no_Ippo__New_Challenger',
  'anime_score': '8.74',
  'id': 39,
  'name': 'Hajime no Ippo: New Challenge'},
 {'anime_description': "That jumbled piece of architecture, that cacophony of hissing steam and creaking joints, with smoke billowing from it as it moves on its own... That castle is home to the magnificent wizard Howl, infamous for both his magical prowess and for being a womanizer—or so the rumor goes in Sophie Hatter's small town. Sophie, as the plain daughter of a hatmaker, does not expect much from her future and is content with working hard in the shop. \n\r\nHowever, Sophie's simple life takes a turn for the exciting when she is ensnared in a disturbing situation, and the mysterious wizard appears to rescue her. Unfortunately, this encounter, brief as it may be, spurs the vain and vengeful Witch of the Waste—in a fit of jealousy caused by a past discord with Howl—to put a curse on the maiden, turning her into an old woman.\n\r\nIn an endeavor to return to normal, Sophie must accompany Howl and a myriad of eccentric companions—ranging from a powerful fire demon to a hopping scarecrow—in his living castle, on a dangerous adventure as a raging war tears their kingdom apart.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Adventure', 'Drama', 'Fantasy', 'Romance'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/5/75810.jpg',
  'anime_link': 'https://myanimelist.net/anime/431/Howl_no_Ugoku_Shiro',
  'anime_score': '8.74',
  'anime_video': 'https://www.youtube.com/embed/iwROgK94zcM',
  'id': 40,
  'name': 'Howl no Ugoku Shir'},
 {'anime_description': 'Takashi Natsume, the timid youkai expert and master of the Book of Friends, continues his journey towards self-understanding and acceptance with the help of friends both new and old. His most important ally is still his gluttonous and sake-loving bodyguard, the arrogant but fiercely protective wolf spirit Madara—or Nyanko-sensei, as Madara is called when in his usual disguise of an unassuming, pudgy cat.\n\r\nNatsume, while briefly separated from Nyanko-sensei, is ambushed and kidnapped by a strange group of masked, monkey-like youkai, who have spirited him away to their forest as they desperately search for the Book of Friends. Realizing that his "servant" has been taken out from right under his nose, Nyanko-sensei enlists the help of Natsume\'s youkai friends and mounts a rescue operation. However, the forest of the monkey spirits holds many dangerous enemies, including the Matoba Clan, Natsume\'s old nemesis.\n\r\nStretching from the formidable hideout of the Matoba to Natsume\'s own childhood home, Natsume Yuujinchou Shi is a sweeping but familiar return to a world of danger and friendship, where Natsume will finally confront the demons of his own past.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Slice of Life',
   'Supernatural',
   'Drama',
   'Fantasy',
   'Shoujo'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/3/37449.jpg',
  'anime_link': 'https://myanimelist.net/anime/11665/Natsume_Yuujinchou_Shi',
  'anime_score': '8.74',
  'anime_video': 'https://www.youtube.com/embed/n_Ku789_xVo',
  'id': 41,
  'name': 'Natsume Yuujinchou Sh'},
 {'anime_description': 'The anime adaptation of the final Mushishi manga arc. Ginko stumbles upon a young girl in a mountain with branches and leaves growing out of her body. He later realises that she is the lord of that mountain but finds it strange that a human like her was chosen as the lord. He later meets her older brother who has continued to search for her ever since she disappeared while she was accompanying him on a stormy day. The story is about that girl, Kaya, and how she is torn between continuing her duty as a mushi lord and returning back to her loving human family.\n\r\n(Source: ANN)',
  'anime_genre': ['Slice of Life',
   'Adventure',
   'Fantasy',
   'Supernatural',
   'Historical',
   'Mystery',
   'Seinen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/9/72689.jpg',
  'anime_link': 'https://myanimelist.net/anime/28957/Mushishi_Zoku_Shou__Suzu_no_Shizuku',
  'anime_score': '8.72',
  'anime_video': 'https://www.youtube.com/embed/BDdPKndfd68',
  'id': 42,
  'name': 'Mushishi Zoku Shou: Suzu no Shizuk'},
 {'anime_description': "Onto their third serialization, manga duo Moritaka Mashiro and Akito Takagi—also known by their pen name, Muto Ashirogi—are ever closer to their dream of an anime adaption. However, the real challenge is only just beginning: if they are unable to compete with the artist Eiji Niizuma in the rankings within the span of six months, they will be cancelled. To top it off, numerous rivals are close behind and declaring war. They don't even have enough time to spare thinking about an anime!\n\r\nIn Bakuman. 3rd Season, Muto Ashirogi must find a way to stay atop the colossal mountain known as the Shounen Jack rankings. With new problems and new assistants, the pair continue to strive for their dream.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Comedy', 'Drama', 'Romance', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/6/41845.jpg',
  'anime_link': 'https://myanimelist.net/anime/12365/Bakuman_3rd_Season',
  'anime_score': '8.69',
  'id': 43,
  'name': 'Bakuman. 3rd Seaso'},
 {'anime_description': 'As the Fourth Holy Grail War rages on with no clear victor in sight, the remaining Servants and their Masters are called upon by Church supervisor Risei Kotomine, in order to band together and confront an impending threat that could unravel the Grail War and bring about the destruction of Fuyuki City. The uneasy truce soon collapses as Masters demonstrate that they will do anything in their power, no matter how despicable, to win.\n\r\nSeeds of doubt are sown between Kiritsugu Emiya and Saber, his Servant, as their conflicting ideologies on heroism and chivalry clash. Meanwhile, an ominous bond forms between Kirei Kotomine, who still seeks to find his purpose in life, and one of the remaining Servants. As the countdown to the end of the war reaches zero, the cost of winning begins to blur the line between victory and defeat.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Action', 'Supernatural', 'Thriller', 'Fantasy'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/8/41125.jpg',
  'anime_link': 'https://myanimelist.net/anime/11741/Fate_Zero_2nd_Season',
  'anime_score': '8.69',
  'anime_video': 'https://www.youtube.com/embed/FkZ1euZ-S-Y',
  'id': 44,
  'name': 'Fate/Zero 2nd Seaso'},
 {'anime_description': "Dr. Kenzou Tenma is a renowned brain surgeon of Japanese descent working in Europe. Highly lauded by his peers as one of the great young minds that will revolutionize the field, he is blessed with a beautiful fiancée and is on the cusp of a big promotion in the hospital he works at. But all of that is about to change with a grave dilemma that Kenzou faces one night—whether to save the life of a small boy or that of the town's mayor. Despite being pressured by his superiors to perform surgery on the mayor, his morals force him to perform the surgery on the other critical patient, saving his life and forfeiting the mayor's. A doctor is taught to believe that all life is equal; however, when a series of murders occur in the surgeon's vicinity, all of the evidence pointing to the boy he saved, Kenzou's beliefs are shaken. Along his journey to unravel the true identity of his little patient, Kenzou discovers that the fate of the world may be intertwined with the mysterious child.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Drama',
   'Horror',
   'Mystery',
   'Police',
   'Psychological',
   'Seinen',
   'Thriller'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/10/18793.jpg',
  'anime_link': 'https://myanimelist.net/anime/19/Monster',
  'anime_score': '8.69',
  'anime_video': 'https://www.youtube.com/embed/9aS-EgdAq6U',
  'id': 45,
  'name': 'Monste'},
 {'anime_description': 'There are words Violet heard on the battlefield, which she cannot forget. These words were given to her by someone she holds dear, more than anyone else. She does not yet know their meaning.\n\r\nA certain point in time, in the continent of Telesis. The great war which divided the continent into North and South has ended after four years, and the people are welcoming a new generation.\n\r\nViolet Evergarden, a young girl formerly known as "the weapon," has left the battlefield to start a new life at CH Postal Service. There, she is deeply moved by the work of "Auto Memories Dolls," who carry people\'s thoughts and convert them into words.\n\r\nViolet begins her journey as an Auto Memories Doll, and comes face to face with various people\'s emotions and differing shapes of love. All the while searching for the meaning of those words.\n\r\n(Source: Anime Expo)\n\nEpisode 1 was previewed at a screening at Anime Expo on July 2, 2017. Regular broadcasting will begin in January 2018.',
  'anime_genre': ['Drama', 'Fantasy'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/8/86269.jpg',
  'anime_link': 'https://myanimelist.net/anime/33352/Violet_Evergarden',
  'anime_score': '8.69',
  'anime_video': 'https://www.youtube.com/embed/M_Zdfcdl3mg',
  'id': 46,
  'name': 'Violet Evergarde'},
 {'anime_description': "A shinigami, as a god of death, can kill any person—provided they see their victim's face and write their victim's name in a notebook called a Death Note. One day, Ryuk, bored by the shinigami lifestyle and interested in seeing how a human would use a Death Note, drops one into the human realm.\n\r\nHigh school student and prodigy Light Yagami stumbles upon the Death Note and—since he deplores the state of the world—tests the deadly notebook by writing a criminal's name in it. When the criminal dies immediately following his experiment with the Death Note, Light is greatly surprised and quickly recognizes how devastating the power that has fallen into his hands could be.            \n\r\nWith this divine capability, Light decides to extinguish all criminals in order to build a new world where crime does not exist and people worship him as a god. Police, however, quickly discover that a serial killer is targeting criminals and, consequently, try to apprehend the culprit. To do this, the Japanese investigators count on the assistance of the best detective in the world: a young and eccentric man known only by the name of L.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Mystery',
   'Police',
   'Psychological',
   'Supernatural',
   'Thriller'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/9/9453.jpg',
  'anime_link': 'https://myanimelist.net/anime/1535/Death_Note',
  'anime_score': '8.68',
  'anime_video': 'https://www.youtube.com/embed/Vt_3c8BgxV4',
  'id': 47,
  'name': 'Death Not'},
 {'anime_description': "The students return as school is back in session for the second semester. Following their exploits on the island during summer vacation, Class 3-E continues to sharpen their blades with their sights set on their teacher, the slippery Koro-sensei. They have more to worry about than just their teacher, however, as enemy assassins, both old and new, are out for the increased bounty on the octopus' head.\n\r\nMoreover, their rivals in Class A, as well as Kunugigaoka Junior High's fearsome principal, stand to block Class E from achieving academic excellence. With all of these obstacles opposing them, the group must continue to work together in order to overcome their foes and accomplish their goal of successfully assassinating their teacher.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Action', 'Comedy', 'School', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/8/77966.jpg',
  'anime_link': 'https://myanimelist.net/anime/30654/Ansatsu_Kyoushitsu_TV_2nd_Season',
  'anime_score': '8.67',
  'anime_video': 'https://www.youtube.com/embed/tZiHgr0kd7E',
  'id': 48,
  'name': 'Ansatsu Kyoushitsu (TV) 2nd Seaso'},
 {'anime_description': 'Inspired after watching a volleyball ace nicknamed "Little Giant" in action, small-statured Shouyou Hinata revives the volleyball club at his middle school. The newly-formed team even makes it to a tournament; however, their first match turns out to be their last when they are brutally squashed by the "King of the Court," Tobio Kageyama. Hinata vows to surpass Kageyama, and so after graduating from middle school, he joins Karasuno High School\'s volleyball team—only to find that his sworn rival, Kageyama, is now his teammate.\n\r\nThanks to his short height, Hinata struggles to find his role on the team, even with his superior jumping power. Surprisingly, Kageyama has his own problems that only Hinata can help with, and learning to work together appears to be the only way for the team to be successful. Based on Haruichi Furudate\'s popular shounen manga of the same name, Haikyuu!! is an exhilarating and emotional sports comedy following two determined athletes as they attempt to patch a heated rivalry in order to make their high school volleyball team the best in Japan.\n\r\n[Written by MAL Rewrite]',
  'anime_genre': ['Comedy', 'Sports', 'Drama', 'School', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/7/76014.jpg',
  'anime_link': 'https://myanimelist.net/anime/20583/Haikyuu',
  'anime_score': '8.67',
  'anime_video': 'https://www.youtube.com/embed/JOGp2c7-cKc',
  'id': 49,
  'name': 'Haikyuu!'},
 {'anime_description': "Japanese Featherweight Champion Makunouchi Ippo has defended his title belt once more with the help of his devastating signature move: the Dempsey Roll. However, new challengers are rising up left and right, claiming to have an answer for the move responsible for crushing his opponents. Will Ippo be able to step up to the challenge, or will the weight of his pride destroy him before he finds out just what it means to be strong? Meanwhile, fellow Kamogawa Gym mate Aoki Masaru is just a hop, skip, and a Frog Punch away from claiming his own belt, ready to take on the Japanese Lightweight Champion!\n\nHajime no Ippo: Rising continues Ippo's quest to become stronger, featuring the same cast of loveable dimwits from Kamogawa Gym, as they put their bodies and hearts on the line to make their way in the harsh world of professional boxing. With a will of iron, Ippo steps into the ring once again.\n\r\n[Written by MAL Rewrite]",
  'anime_genre': ['Comedy', 'Sports', 'Drama', 'Shounen'],
  'anime_image': 'https://myanimelist.cdn-dena.com/images/anime/6/56147.jpg',
  'anime_link': 'https://myanimelist.net/anime/19647/Hajime_no_Ippo__Rising',
  'anime_score': '8.67',
  'id': 50,
  'name': 'Hajime no Ippo: Risin'}];
    return { animes };
  }
}
